.\" Process this file with
.\" groff -man -Tascii man
.\"

.TH TTLOGN 1 "MARCH 2014"

.SH NAME
ttlogn \- Timetracker LogN

.SH DESCRIPTION
ttlogn is a software that helps the worker managing his tasks. 
It shows and manage the tasks finished and to do, of the worker 
in an easy way. Also it helps the with the log of his tasks in 
a Timetracker.

.SH SYNOPSIS
.IP --help
.IP login
.IP "add repo"
.IP "delete repo"
.IP ls 
[-d|-w|-m]
.IP save 
[-d|-w|-m]
.IP "add entry"
.IP "modify entry"
.IP "delete entry"
.IP clients
.IP "story ls" 
[-a]
.IP "delete story"

.SH OPTIONS
.IP --help
Prints the help.
.IP "login" 
Saves the credentials of the user.
.IP "ls [-d|-w|-m]" 
List the commits in a period of time.
.IP "save [-d|-w|-m]"
Saves the commits of Github in the Timetracker.
.IP "add repo"
Binds a repository to a project of the Timetracker.
.IP "delete repo"
Delete an existing repository in the configuration file
.IP "add entry"
Add new entry in the Timetracker. 
.IP "modify entry"
Modify an existing entry in the Timetracker. 
.IP "delete entry"
Delete an existing entry in the Timetracker.
.IP clients 
List the clients of an User in the Timetracker.
.IP "story ls [-a]"
List the Pivotal's stories of an user.
.IP "delete story"
Delete an existing story in Pivotal Tracker.

.SH FILES
.IP ~/.ttlogn
The configuration file of ttlogn. 

.SH ENVIRONMENT
.IP TT_ENV
Flag to know what Data Base to use.

.SH BUGS

.SH AUTHOR
Daniel Solis
