.\" Process this file with
.\" groff -man -Tascii ttlogn.1
.\"
.TH TTLOGN 1 "MARCH 2014"

.SH NAME
ttlogn \- Timetracker LogN

.SH DESCRIPTION
.B ttlogn
is a software that helps the worker with managing of tasks.
It shows the tasks finished and to do, of the worker in an easy way.
Also it helps the with the log of his tasks in a Timetracker.

.SH OPTIONS
.IP "login" 
Saves the credentials of the user.
.IP "ls" 
List the commits in a period of time.
.IP "save"
Saves the commits of Github in the Timetracker.
.IP "add repo"
Binds a repository to a project of the Timetracker.
.IP "delete repo"
Delete an existing repository in the configuration file
.IP "add task"
Add new task in the Timetracker. 
.IP "modify task"
Modify an existing task in the Timetracker. 
.IP "delete task"
Delete an existing task in the Timetracker.
.IP clients 
List the clients of an User in the Timetracker.
.IP "list stories"
List the Pivotal's stories of an user.

.SH FILES
.I ~/.ttlogn
The configuration file of ttlogn. 

.SH ENVIRONMENT
.IP TT_ENV
Flag to know what Data Base to use.

.SH BUGS

.SH AUTHOR
Daniel Solis

